services:

  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - bookstack_db_:/config
    restart: unless-stopped

  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack_app
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - APP_URL=https://epll-wiki.onrender.com
      - APP_KEY=${APP_KEY}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bookstackapp
      - DB_USERNAME=bookstack
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - bookstack_app_:/config
    ports:
      - 6875:80
    depends_on:
      - db
    restart: unless-stopped

volumes:
  bookstack_db_:
  bookstack_app_:
